### ISSUE TITLE
LocateAnchorStatus meanings unclear

### ISSUE THREAD

**Issue by jokokojote** [Azure/azure-spatial-anchors-samples#100]
I am wondering what the different enum values of LocateAnchorStatus actually mean and when they occur. The documentation is not really providing extensive information (https://docs.microsoft.com/en-us/cpp/api/spatial-anchors/winrt/locateanchorstatus). 

I have played around with the unity example on HoloLens and placed different anchors in different places and walked around in the area. `LocateAnchorStatus.AlreadyTracked `, `LocateAnchorStatus.NotLocated `, and `LocateAnchorStatus.NotLocatedAnchorDoesNotExist` never occured when `AnchorLocated ` event arrised. 

I thought `LocateAnchorStatus.AlreadyTracked` maybe occurs when the HoloLens detects an anchor again after some time in which it could not find any of the anchors features because real world objects obstructed the view. But this does not seem to be the case.

**Comment by pjar-msft** [comment]
Thanks for the feedback. We are looking into how this documentation might be improved.


In the meantime, here's a rough explanation:
Unless your changes have diverged unrecognizably from the sample, we wouldn't expect the sample to give anything but Located.

- Located = "We found the anchor." The CloudSpatialAnchor will have a local anchor attached that you can use.
- AlreadyTracked = "We already gave you this anchor via Located, and you asked for it again, so here it is again." If you don't want this to happen, you can set BypassCache to true and we'll look for the anchor again and it will have status Located when we give it to you. This shouldn't be expected in the sample because of the way it uses a single CloudSpatialAnchorWatcher. 
- DoesNotExist = "You passed in an anchor with a bad ID or which otherwise doesn't exist in your account."
- NotLocated = Exists for legacy reasons, this shouldn’t be expected because it's a hold over from a request->response world that the SDK no longer uses.

**Comment by julianparismorgan** [comment]
Hey @jokokojote, you can also find similar descriptions as code comments on this docs page: https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/create-locate-anchors-unity#locate-a-cloud-spatial-anchor

If it's okay with you, we'll go ahead and close this issue!

**Comment by robbbbbb** [comment]
It's a year later, and, having just been bitten by pretty much the same issue here, it would be really helpful if you could improve the documentation around this.

On HoloLens, when the AnchorLocatedEventArgs.Status value is AlreadyTracked, the key piece of information is that the associated AnchorLocatedEventArgs.Anchor will **not** be in a coherent state to call functions like GetPose() or to be passed in to a CloudNativeAnchor.CloudToNative(cloudAnchor) call. Attempts to do so will fail because AnchorLocatedEventArgs.Anchor (which is an instance of CloudSpatialAnchor) will have a LocalAnchor (a native pointer) value of NULL. None of the documentation is sufficiently explicit about this to be useful. 

It's quite clear from this and multiple previous issues (https://github.com/Azure/azure-spatial-anchors-samples/issues/295, https://github.com/Azure/azure-spatial-anchors-samples/issues/252) that this **does** confuse people and neither the samples in this repo, the (very scant) [documentation here](https://docs.microsoft.com/en-us/cpp/api/spatial-anchors/winrt/locateanchorstatus) nor [this section of prose](https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/create-locate-anchors-unity#locate-a-cloud-spatial-anchor) are really helping.

The samples, depending on what they're doing, either ignore this AlreadyTracked case entirely, or handle it and just have a comment or a log line such as "Already found this anchor".

What would be much more helpful would be to give an explicit example of how the previously obtained CloudSpatialAnchor instance (from a previous callback to SpatialAnchorManager.AnchorLocated) should be cached and re-used.

**Comment by Varnauld** [comment]
Hello and thank you for the feedback! Tagging @pamistel to review, thanks!
