### ISSUE TITLE
Unable to use RecommendedForCreateProgress when creating multiple anchors

### ISSUE THREAD

**Issue by JeanVACCA** [Azure/azure-spatial-anchors-samples#11]
On Unity Android, I'm trying to create multiple anchors in same session but the value of RecommendedForCreateProgress does not reset after I create one; 
So when I call CreateAnchorAsync, I have to wait and collect data near my created anchor but without any clue or status; I have also noticed that in this case my anchor is not create where I place it.

**Comment by vriveras** [comment]
@JeanVACCA , Yes the sufficiency level will not reset per anchor save we will keep adding frames as you move and use the device tracker. You can see if you moved enough the sufficiency will go down util we collect more data but it will never go to zero this is by design. All anchors created in one session are getting linked together. 
 
You can visualize the sufficiency using the SessionUpdated callback using ReadyForCreateProgress and RecommendedForCreateProgress values.

This is the Unity snippet that gets the values in the sample.
``` c#
 private void CloudSpatialAnchorSession_SessionUpdated(object sender, SessionUpdatedEventArgs args)
 {
     SessionStatusIndicators[(int)SessionStatusIndicatorType.ReadyForCreate] = args.Status.ReadyForCreateProgress;
     SessionStatusIndicators[(int)SessionStatusIndicatorType.RecommendedForCreate] = args.Status.RecommendedForCreateProgress;

     OnSessionUpdated?.Invoke(sender, args);
 }
```

**Comment by JeanVACCA** [comment]
Thanks for your answer but what's about the delay during the **CreateAnchorAsync**, How can I give feedback to my user about the data collected ?

**Comment by vriveras** [comment]
@JeanVACCA , I am not sure I understand the question. What do you mean delay on CreateAnchorAsync and what feedback do you want to provide to the user?

**Comment by vriveras** [comment]
Closing issue no response
