### ISSUE TITLE
Suggestion: can you please dependencies versions clearly in download page?

### ISSUE THREAD

**Issue by clifflinmao** [Azure/azure-spatial-anchors-samples#122]
Can you please describe the dependencies versions clearly in the below page so that when use download the unit package they won'd get compile error? 
- AR Foundation version?
- ARKit plugin version?
- ARCore plugin version?
- others?
https://github.com/Azure/azure-spatial-anchors-samples/releases

Or do I understand correctly that in general the ASA version (e.g.2.1.1) is intentionally named as same as the depending AR foundation version?

**Comment by craigktreasure** [comment]
@clifflinmao The version number of Azure Spatial Anchors is not intentionally aligned with AR Foundation. Since that's not the case and to avoid confusion like this, I think listing the versions for the AR Foundation dependencies sounds like a good idea. I'll get those added and we'll try to keep adding those in the future.

For reference, you can take a look at our Unity sample [package manifest](https://github.com/Azure/azure-spatial-anchors-samples/blob/master/Unity/Packages/manifest.json) to find what we're currently known to be compatible with.

https://github.com/Azure/azure-spatial-anchors-samples/blob/92a577e9ed35d1530c15eeae10f6820ccb71a0d7/Unity/Packages/manifest.json#L10-L14

**Comment by craigktreasure** [comment]
The [latest release](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.1.1) has been updated with the Unity dependency version numbers.

**Comment by clifflinmao** [comment]
Thank you !
