### ISSUE TITLE
Not Enough Spatial Data problem

### ISSUE THREAD

**Issue by frsprojects** [Azure/azure-spatial-anchors-samples#127]
After many attempts to make a version of SpectatorView functional using UNet, I was able to successfully communicate between client / server using Azure Spatial Anchor to share anchor information. Many errors have occurred, including an unknown error, which appears to resolve the deletion of the MRTK 2.2.0 library. This has already been resolved, but now at random a problem occurs in the function **CloudManager.CreateAnchorAsync**, which says just like this: Not enough Neighborhood Spatial Data was available to complete the desired Create operation.

This problem does not happen directly, but randomly makes it impossible to find a pattern to try to think of a solution to this problem.

Remembering that the CloudManager.SessionStatus.RecommendedForCreateProgress variable is above 1 before calling the creation function.

Could you give me more information about this problem? What do I do to not do a project to solve it?

**Comment by mschofie** [comment]
The `CloudManager.CreateAnchorAsync` call will fail with the `Not enough Neighborhood Spatial Data was available to complete the desired Create operation` error if the Azure Spatial Anchors SDK hasn't processed enough frames to have sufficient data to build a representation of the Anchor to upload to the cloud. If you take a look at the sample, [DemoScriptBase.cs](https://github.com/Azure/azure-spatial-anchors-samples/blob/92a577e9ed35d1530c15eeae10f6820ccb71a0d7/Unity/Assets/AzureSpatialAnchors.Examples/Scripts/DemoScriptBase.cs#L444) has the following logic in `SaveCurrentObjectAnchorToCloudAsync`:

```C#
    while (!CloudManager.IsReadyForCreate)
    {
        await Task.Delay(330);
        float createProgress = CloudManager.SessionStatus.RecommendedForCreateProgress;
        feedbackBox.text = $"Move your device to capture more environment data: {createProgress:0%}";
    }
```

It uses the `CloudManager.IsReadyForCreate` property (which is simply checking `CloudManager.SessionStatus.RecommendedForCreateProgress` to see if it's greater than or equal to 1) to gate whether it actually performs the save with `CloudManager.CreateAnchorAsync`. If there isn't enough data to create an anchor it updates the UI to encourage the user to capture more environment data. Are you seeing the 'Not enough data...' error even after `CloudManager.SessionStatus.RecommendedForCreateProgress` is above 1?

**Comment by frsprojects** [comment]
>Are you seeing the 'Not enough data...' error even after `CloudManager.SessionStatus.RecommendedForCreateProgress` is above 1?

Yes, the error appears even with the recommendation above 1. In this test, I just modified the `AzureSpatialAnchorsBasicDemoScript.cs` script so that through a function I can perform all the steps to save the anchorage. Remembering that, there are moments that you save successfully, in others the failure occurs.

**Comment by mschofie** [comment]
When using the device to scan the space - to drive the 'RecommendedForCreateProgress' up - are you moving (i.e. translating in space) from the point where you started the session? The Azure Spatial Anchors SDK processes frames within 5 meters from current location in order to create an anchor - if you've moved then your 'RecommendedForCreateProgress' _can_ drop, because there aren't a sufficient number of frames within 5 meters. If you try - for example - the NDK sample you can reproduce this by scanning to drive the 'RecommendedForCreateProgress' up, then walking away from where you started, and see the progress drop down.

So even if you've got above 1.0 for 'RecommendedForCreateProgress', if there's a drop in progress, that would cause a "Not enough data...". Could that be what you're seeing? In which case, your app might need to handle this? I'll add a backlog item to at least document this, or add handling to a sample.

**Comment by frsprojects** [comment]
Sometimes, when the process fails, when it reaches the scan stage or the environment, it passes `RecommendedForCreateProgress` as greater than 1 without the same floor, going to the upload step to Azure, causing a failure. Restarting the application (without changing any code), it asks to scan the environment and does not skip a step. Remembering that only a few changes were made to the sample project. Basically a function was created to perform as steps that were used manually automatically. The code:

```cs

        private async Task ProcessAnchorAsync()
        {
                UnityDispatcher.InvokeOnAppThread(() =>
                {
                    UIManager.SetMessage($"Criando sessão...", -1);
                });
                if (CloudManager.Session == null)
                {
                    await CloudManager.CreateSessionAsync();
                }
                currentAnchorId = "";
                currentCloudAnchor = null;

                UnityDispatcher.InvokeOnAppThread(() =>
                {
                    UIManager.SetMessage($"Configurando sessão...", -1);
                });
                ConfigureSession();

                UnityDispatcher.InvokeOnAppThread(() =>
                {
                    UIManager.SetMessage($"Iniciando sessão...", -1);
                });
                await CloudManager.StartSessionAsync();

                UnityDispatcher.InvokeOnAppThread(() =>
                {
                    UIManager.SetMessage($"Salvando ancoragem...", -1);
                });
                //Função que envia a ancoragem
                await SaveCurrentObjectAnchorToCloudAsync();
                CloudManager.StopSession();
        }
```

**Comment by sublimeRich** [comment]
Using SDK 2.2.0 on Android, I'm also hitting this issue; I get the `NotEnoughSpatialData` error, even though `RecommendForCreateProgress >= 1`.

Is it possible that `RecommendForCreateProgress` can drop below 1 after I've called `CreateAnchorAsync`?  And so I'd need to abort that call, resume scanning until `RecommendForCreateProgress >= 1` and then call `CreateAnchorAsync` again?

**Comment by codemaker2015** [comment]
If it occurs in unity then it is due to the wrong version of arfoundation or arcore packages. 
Azure Spatial Anchor requires the following versions 

Unity 2019.1
AR Foundation: 2.1.4
ARCore XR Plugin: 2.2.0
ARKit XR Plugin 2.1.1

**Comment by RamonArguelles** [comment]
Hi @frsprojects, thanks a lot for reporting! Have you been able to double check the version of ASA SDK, Unity, AR Foundation & ARCore? As @mschofie mentioned, the value returned by RecommendedForCreateProgress can go up and down as you are scanning your environment, depending many factors, including the speed in which your device is moving. In the original sample code, since each step is performed manually, you technically have more granular control between scanning your environment, and hence reaching RecommendedForCreateProgress > 1, and calling CreateAnchorAsync. Aka, once you have a good enough scan, it's more likely that you'll stop moving your device, while you proceed to the anchor creation call. Once you change your app code so that steps are performed automatically, it is likely you might continue to move your device around after you hit RecommendedForCreateProgress > 1, but before or during the call to CreateAnchorAsync. So, if RecommendedForCreateProgress were to fall under 1 during that period, the call to CreateAnchorAsync could fail. If that's your scenario, you might need to handle this scenario in your app (basically, check RecommendedForCreateProgress, and retry CreateAnchorAsync again once it reaches > 1.
