### ISSUE TITLE
Unity HoloLens sample freezing at "Looking for Anchors" step

### ISSUE THREAD

**Issue by reneschulte** [Azure/azure-spatial-anchors-samples#2]
Hi,

The Unity HoloLens sample is stuck at one stage if its not build with Unity C# Projects as output.

I basically just tapped through the Basic scene demo. It all worked well and I see the anchor upload worked in the Azure Portal so Key and ID should be fine. Later it is stuck in "Looking for Anchor..." 

It is sporadically and looks like some race condition / Heisenbug. When you build with C# projects and attach a debugger it all works fine but not when in Release mode without C# projects build in Unity.
At one point I saw the below exception, one of those when you try to access UI elements on a background thread, so it might just be that the event callbacks need to dispatch to the UI thread when accessing UI elements. 

```
An unhandled exception of type 'UnityEngine.UnityException' occurred in UnityEngineProxy.dll
get_isActiveAndEnabled can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
```

![exception](https://user-images.githubusercontent.com/7439129/53514379-eb2cde80-3ac7-11e9-9c96-12606da7187b.JPG)

**Comment by vriveras** [comment]
@reneschulte Thank you for reaching out. We are investigating this issue and will get back to you with findings.

**Comment by vriveras** [comment]
@reneschulte , we found a problem on the callback we have in the sample when receiving an error from the API. This will fix the error you are getting which is a threading problem. 

We are working to fix the samples on our side. 

Please modify the code inside DemoScriptBase.cs in the method CloudManager_OnSessionError to the following code.

```csharp
     private void CloudManager_OnSessionError(object sender, SessionErrorEventArgs args)
     {
        Debug.Log(args.ErrorMessage);
        QueueOnUpdate(() =>
        {
            this.isErrorActive = true;
            this.feedbackBox.text = string.Format("Error: {0}", args.ErrorMessage);
        });
     }
```
You might still run into an issue since it failed notifying an error. If you experience an error after this change please share the logs collected from a run after the code change is done. This will give us details with the correct error information.

**Comment by reneschulte** [comment]
Thanks @vriveras I think that was it since this error did not pop up when I tried more yesterday and I think the service was a bit more unstable last week causing that issue.
