### ISSUE TITLE
Are CocoaPods still required on iOS?

### ISSUE THREAD

**Issue by genereddick** [Azure/azure-spatial-anchors-samples#220]
Previously (https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-ios?tabs=openproject-swift) you required CocoaPods to be installed in order to deploy the ASA code on iOS.

The latest version of this doc (https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-ios) no longer mention pods. And, using ASA 2.6 I was able (for the first time) to deploy and create anchors using the xcode project file rather than workspace.

Can you confirm, or point to a post, that pods are no longer required or any other explanation?

**Comment by kaysabelle** [comment]
Hi @genereddick, there are two different development scenarios here.

When using Azure Spatial Anchors in a Swift or Objective-C iOS application created only with Xcode, you will still need to use Cocoapods to install the Azure Spatial Anchors SDK into your project. This is the scenario outlined in the first link you posted.

Since release 2.5.0, the Azure Spatial Anchors Unity SDK was made available as a set of Unity Package Manager (UPM) packages. When you configure your Unity iOS project to use the ASA SDK for iOS, you do not need to use Cocoapods to install the SDK. This is the scenario outlined in the second link you posted.

Hope this provides some clarity.

**Comment by genereddick** [comment]
@kaysabelle that's clear. Thanks!
