### ISSUE TITLE
Can I redistribute part of the sample code of azure spatial anchors samples ?

### ISSUE THREAD

**Issue by nikhilsawlani** [Azure/azure-spatial-anchors-samples#240]
Hi so we thought of integrating Azure spatial anchor services with our [SDK ](https://github.com/arway-app/Developer_Unity_SDK) and for this, we need to redistribute part of the spatial anchor code with our SDK.

I saw the MIT License on this repo, so it seems it is possible if we maintain the copyrights.

**Comment by msftradford** [comment]
Thanks for the inquiry @nikhilsawlani! We are working to get your question answered and will let you know as soon as we have something definitive.

**Comment by nikhilsawlani** [comment]
Hi, @msftradford any update on this thread? Thanks

**Comment by pamistel** [comment]
Hi @nikhilsawlani 
From a legal point of view, Microsoft requires a direct contractual relationship to the end-user of our SDK. In order to achieve this, ideally you would link to our SDK and have people agree to our EULA. Only official Microsoft partners can redistribute Azure Service Components. More info [here](https://www.microsoft.com/en-us/us-partner-blog/2020/10/22/how-to-become-a-microsoft-partner/)

**Comment by nikhilsawlani** [comment]
Hi @pamistel 

Thanks for the response, in the case of "official Microsoft partners" which we have registered for, will it be still mandatory for our SDK users to sign EULA with Azure or that’s not needed when service is distributed by official Microsoft partners?
