### ISSUE TITLE
WindowsMRXRSDK.pdb not loaded

### ISSUE THREAD

**Issue by GuoweiST** [Azure/azure-spatial-anchors-samples#261]
**Description**

A clear and concise description of what the issue is.

I was following the steps indicated [here](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-hololens?tabs=azure-portal) and is stuck at the "Deploy the HoloLens application"

When I click on Start debugging, VS prompted me a that WindowsMRXRSDK.pdb not loaded as shown in the image below.

![image](https://user-images.githubusercontent.com/83278844/116638937-f4f94780-a999-11eb-8c70-2f77e9105875.png)

The HoloLens 2 will start up the application but nothing is shown.

My Build Settings 
![image](https://user-images.githubusercontent.com/83278844/116637547-c75ecf00-a996-11eb-915a-ec10a160f5d2.png)

Development Information: 
ASA SDK Core Version 2.9.0
ASA SDK for Windows Version 2.9.0
Azure Object Anchors 0.9.0
Azure Remote Rendering 1.0.6

Unity 2019.4.21f1
Visual Studio 2019

AR Device information
HoloLens 2
OS build: 10.0.19041.1140

**Comment by willyeo** [comment]
Thanks for your patience and making this as a separate issue!

In the [instruction page](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-hololens?tabs=azure-portal) you're following, there's requirement:

> You need a Windows computer with Unity (LTS) and Visual Studio 2019 or later installed. Use Unity 2020 LTS with ASA SDK version 2.9 or later (which uses the Unity XR Plug-in Framework) or Unity 2019 LTS with ASA SDK version 2.8 or earlier.

Because you're using Unity 2019.4.21f1, you'll need ASA SDK version 2.8 or earlier. To download the SDK, please refer [this page](https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/setup-unity-project?tabs=unity-package-web-ui#download-asa-packages). Note, I checked again with the "download with browser option" and it's actually possible to choose older versions - please choose "Version" tab as shown below to get the older versions. 

![image](https://user-images.githubusercontent.com/29989947/116755587-7dd6aa00-a9bf-11eb-8331-1a5a3eca198f.png)

Let us know how it works.

**Comment by oafolabi-msft** [comment]
@GuoweiST , would you say we can close this issue for now or, did you run into any problems related to the feedback?
