### ISSUE TITLE
Screen freezes when session start (Unity_Android)

### ISSUE THREAD

**Issue by marklinmao** [Azure/azure-spatial-anchors-samples#28]
I followed the official document to create CloudSpatialAnchorSession, which is same as the steps in AzureSpatialAnchorsDemoWrapper.CreateNewCloudSession(), the screen get frozen when I start the session. I check the sample and found that for Android, it creates the session by calling java class. I just want to confirm, is that for some reason just a temporary workaround ?

-------------code from AzureSpatialAnchorDemoWrapper.cs, creating a session-------------------

            UnityAndroidHelper.Instance.DispatchUiThread(unityActivity =>
            {
                // We should only run the java initialization once
                if (!JavaInitialized)
                {
                    using (AndroidJavaClass cloudServices = new AndroidJavaClass("com.microsoft.CloudServices"))
                    {
                        cloudServices.CallStatic("initialize", unityActivity);
                        JavaInitialized = true;
                    }
                }
                this.CreateNewCloudSession();
            });
----------------------------------------------------------------------------------------

The document that I followed: https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/create-locate-anchors-unity

**Comment by darax** [comment]
hi @marklinmao 
we require the initialization so that we can get the JNIEnv. Some of the native calls to ARCore require this as a parameter.

For your freeze issue, try doing 'assets->reimport all' in Unity and rebuilding.

**Comment by ChrisHorrigan** [comment]
This is happening to me too.  Seems like no matter what I put in my anchor script, if I call that Start function my phone just shows a black screen and ends the process when I tap it.  I feel like it's something in the AzureSpatialAnchorsBridge or deeper rather than in my script that calls the start function.  It formerly worked with hololens (this tutorial https://docs.microsoft.com/en-us/azure/spatial-anchors/tutorials/tutorial-new-unity-hololens-app) and I've been trying to adapt it for Android.

Reimporting all and rebuilding didn't fix it for me.
