### ISSUE TITLE
objects dont move after find azure spatial anchor in the shared session 

### ISSUE THREAD

**Issue by wenqian157** [Azure/azure-spatial-anchors-samples#307]
**Description**

I was follow the tutorial: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-05

After deploy, everything works but the last step, ''on device 2 press Get Azure Anchor''. In the debug window it prints "Local anchor position successfully set to Azure anchor position" but the object doesnt really move. 

I checked the code and compared it with the code from another tutorial in which the relocating works: https://docs.microsoft.com/en-gb/learn/modules/azure-spatial-anchors-tutorials/3-exercise-get-started-with-azure-spatial-anchors

It seems some operations might be missing in AnchorModuleScript.cs so I copyed those lines to it as below:
![image](https://user-images.githubusercontent.com/44199787/136418610-d9aa8295-2b23-4721-9637-8f855cdfbff9.png)

It solved the issue for me for now. Not sure if this happens to other people or if this is the best solution.

**Comment by phamqduc** [comment]
Thank you for sharing with us your observation of the issue. I'm glad that you have a way to resolve it at your end.

Since this is directly relevant to the tutorial, may I suggest that you post this question/suggestion onto the tutorial page?

If you scroll down to the end of the tutorial page, there is a button to provide feedback as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/2096755/136598857-8f8a2f85-23be-43f2-862a-dc73bd6f1883.png)

Thanks again for sharing with us and help us to improve.
