### ISSUE TITLE
Finding process stick After the cloud ID has been deleted

### ISSUE THREAD

**Issue by Davidwang007** [Azure/azure-spatial-anchors-samples#308]
version:2.10.2
platform: Android
tool: Unity

After the Cloud id has been deleted for some reason,try to find this cloud id for the second time in the same session then the app will be stuck and can not stop the find processing.

**Comment by phamqduc** [comment]
Hi @Davidwang007, thank you for letting us know your concern about the issue. 
Please kindly let me know if my understanding of the issue below is correct.
The Unity sample app (Android) appears stuck after the the following steps:

1. (Using Basic Demo) Create and save a cloud anchor successfully.
2. Create a new session to locate the anchor. Anchor is located successfully.
3. Delete the cloud anchor and invoke the next step as locating the same anchor (without creating a new session) - this requires changing the sample code.
4. The app is still alive (with active camera feed) but not able to proceed to next steps.

If the above scenario correctly reflects your concern, the app control flow is stuck here because the app state is only updated on successful location of the cloud anchor, as shown inside [`OnCloudAnchorLocated`](https://github.com/Azure/azure-spatial-anchors-samples/blob/79dc2ee96d027f9eeeab56767b5013d533bced63/Unity/Assets/AzureSpatialAnchors.Examples/Scripts/AzureSpatialAnchorsBasicDemoScript.cs#L99),
            `if (args.Status == LocateAnchorStatus.Located) { ...`
               `currentAppState = AppState.DemoStepDeleteFoundAnchor; }`

Even though the _sample_ app by itself does not locate an anchor after deleting it and so does not run into this issue, its simple control flow does not show how to handle program flow when an anchor is not located. I've created an internal issue report to track this and will let you know if we have a fix in the future.
Thanks again.

**Comment by Davidwang007** [comment]
Thank you very much for your reply. In our program,when use Azure Spatial Anchors, after  the cloud anchor (setting the expiration time) being created, the anchor ID will be stored in the database. These anchor IDs will be bound with specific real devices. 

    In our case ,the process of use Spatial Anchor is more complicated than the demo, that is, creating anchors and searching anchors are combined, and sometimes anchor-searching operation happens many times .
The typical workflow is as follows:

    Search Anchor A  -->  Search Anchor B -->  Create Anchor C --> Search Anchor D --> Search Anchor E --> Reset Session --> Search Anchor B --> Create Anchor F

    According to the provided demo, after creating/ searching a spatial anchor each time, we call the following method to release resources :

```csharp
        private void StopAzureCloudSession()
        {
            requreToStopCreateAnchor = true;
            if (currentWatcher != null)
            {
                currentWatcher.Stop();
                currentWatcher = null;
            }
            if (CloudManager != null)
            {
                CloudManager.StopSession();
                CloudManager.ResetSessionAsync();
            }
        }
```


    In the practice, we figured out three problems:

    1. Because the spatial anchor is deleted after expiration (sometimes we don't know, anyway, it is deleted), assuming that anchor ID is A, when we search anchor A at the first time, we will get a prompt showing anchor A has been deleted. If we search anchor A again in the same session, the application will crash.

    2. Sometimes, when the network suddenly disconnected for some reason,in this situation, the following errors will be triggered by searching the cloud anchor:

    “Application did not provide valid credentials and therefore could not authenticate”

    This error is obtained by subscribing to the CloudManager. Error event. After getting this error, any operation ,just like create / search anchors, all will lead to app crash.

    3. In some cases, the continuous searching of spatial anchors tactics is adopted, such as:

       Search Anchor A  -->  walk for a distance  -->  Search Anchor B  -->  walk for a distance  -->  Search Anchor C

    The application will also crash, but this does not necessarily happen at some definite time. It is occasionally.

    Therefore, my question is how to release resources after creating or searching a cloud anchor each time in the same session(or what should we do after each creating / searching operation),which is the right way to achieve the purpose we want? How to ensure our process correctly execute without crash.

    Thank you very much.
