### ISSUE TITLE
Replace Azure Spatial Anchors object in unity app using mobile 

### ISSUE THREAD

**Issue by axlvlv** [Azure/azure-spatial-anchors-samples#309]
Is it possible to replace the cube to be some custom object in the sample Unity code using mobile?

**Comment by msftradford** [comment]
@axlvlv, thanks for reaching out! Check out [this Unity doc page](https://docs.unity3d.com/Manual/InstantiatingPrefabs.html) about instantiating prefabs at run time. Instead of using our built-in in cube prefab, you can create your own and instantiate that instead. You would then modify [this line of the sample](https://github.com/Azure/azure-spatial-anchors-samples/blob/79dc2ee96d027f9eeeab56767b5013d533bced63/Unity/Assets/AzureSpatialAnchors.Examples/Scripts/DemoScriptBase.cs#L502) to use your custom prefab.
