### ISSUE TITLE
Having two Anchors in the scene deletes the gameobject with the anchor

### ISSUE THREAD

**Issue by Spoon2311** [Azure/azure-spatial-anchors-samples#317]
**Description**

when having two different ASAs in a scene, one Gameobject (with the ASA attached to it) it being deleted.

**Steps to reproduce the issue**

Create two gameobjects with ASAs attached to to.
Save the ASAs in your network
Reopen the app and find the ASA of the first object.
Find the ASA of the second object.

**Expected behavior**

Both gameobject should be on the spot where the initial ASA was placed.

**Screenshots**

**Development information (please complete the following information)**

 - OS: Windows
 - Development Platform\Version: Unity 2020.3.19f1
 - Azure Spatial Anchors SDK version: [e.g. `2.9.0`]

**AR Device information (please complete the following information):**

 - Device: HoloLens 2
 - OS: UWP, newest version

**Additional context**
![image](https://user-images.githubusercontent.com/59868550/140790024-161280c1-8085-44a4-9417-6b25b957cabb.png)
![image](https://user-images.githubusercontent.com/59868550/140790069-24c6bd5e-b546-436b-b259-1765e47d011e.png)
![image](https://user-images.githubusercontent.com/59868550/140790111-1255e04c-f960-46e2-b1f6-63d242b1fcca.png)

Here some snippets of the log, showing where the second anchor has been found, then the 2 objects (Betriebsgebaeude & 220kv Schaltanlage) are still found. and on Destroy Session the betriebsgebaeude is destroyed as well and not found anymore.

**Comment by msftradford** [comment]
Hey @Spoon2311, thanks for reaching out! I wonder if you are running into the issue where a destroyed ARAnchor also destroys the GameObject that it is attached to. There is this interesting [setting for an ARAnchor called destroyOnRemoval](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARTrackable-2.html#UnityEngine_XR_ARFoundation_ARTrackable_2_destroyOnRemoval) that I think might be the root cause of the issue. To confirm, in your `CloudManager_AnchorLocated` implementation before calling `CreateNativeAnchor()` on the `GameObject`, can you first call `gameObject.FindNativeAnchor().WorldAnchor.destroyOnRemoval = false;`? Let us know if that helps. Thanks!
