### ISSUE TITLE
Not able to run APIs which get from web app and Azure Spatial Anchors  data to locate that anchor when we close and reopen app.

### ISSUE THREAD

**Issue by RohitJoshi03** [Azure/azure-spatial-anchors-samples#322]
I am using Azure Spatial Anchors for iOS app (in Xcode). I setup all the things in iOS app in swift from Quickstart guide and also setup VisualStudio web app, But i am not able to use APIs which I get from Webapp and not getting data of Spatial Anchors to locate again. And i am doing this from India.

**Comment by phamqduc** [comment]
Hi @RohitJoshi03 , we would like to better understand the issues that you experienced with the following questions.
- Are you able to set up and run iOS Swift _sample_ app, create and locate ASA anchors successfully without any issue?
- Is there any public document related to the VisualStudio web app that you referred to so that we could understand the context and how it is related to Azure Spatial Anchors?
- Are the APIs from Webapp custom-made APIs based on ASA SDK? Are you using these custom APIs in iOS Swift app?

**Comment by RohitJoshi03** [comment]
Let me answer your questions:

1.  Yes, i was able to create and locate ASA anchors without any issue.
2. Yes, here is the reference link : [https://docs.microsoft.com/en-us/azure/spatial-anchors/tutorials/tutorial-share-anchors-across-devices?tabs=azure-portal%2CVS%2CAndroid](url)
3. APIs are not custom made, they were generated automatically. We are not getting any response from APIs, so without knowing about APIs, we can't use them in iOS Swift app. 

![APIs](https://user-images.githubusercontent.com/89076333/143010218-75edaa0c-a997-4e58-920f-4c3c837a2c33.jpg)
