### ISSUE TITLE
Local serialization for lost connectivity? 

### ISSUE THREAD

**Issue by lmaxsmith** [Azure/azure-spatial-anchors-samples#374]
My app is used in is settings where connectivity is sparse. I want to share anchors when available, but store copies locally for instances when no connectivity is available. 
First question: is this something that is possible by default and I just missed it? 
Second question: When I tried to implement my own logic for it, ASA seemed to prevent it because it took over the AR Anchor Manager's behavior so my local anchors wouldn't work. 

What am I missing?

**Comment by Varnauld** [comment]
Hello, thank you for reaching out - tagging @XiangyuL-Microsoft to help here (tracking ID 41668537)

**Comment by XiangyuL-Microsoft** [comment]
@lmaxsmith 
To persistent the anchors, all of them should be stored in Azure. You can try to temporarily cache some anchors, but it is not a recommended solution for now by design. The recommended way is detecting network status and provide real-time function only when the network is available.

Could you please share with us about the detail how ASA prevent you implement your own logic? For example, do you have any sample code?

@Varnauld I would like to consider the local anchor serialization w/o network connectivity as a feature request. How about discuss with engineering team to see if we would provide it in our incoming new SDK?

**Comment by mrwellmann** [comment]
I haven't thought in depth about this but _local anchor serialization w/o network connectivity_ might also make it possible to do more easy or even automatic testing utilizing Unity Mars.

**Comment by Varnauld** [comment]
Hello @lmaxsmith - following up on this issue, were you able to resolve or do you have any follow up questions? 
@XiangyuL-Microsoft  mentioned that you might have a feature request to share with the team, if so, please do share [here](https://feedback.azure.com/d365community/forum/f47d9b25-0725-ec11-b6e6-000d3a4f07b8)
thank you!

**Comment by lmaxsmith** [comment]
No, ASA had too many problems for my implementation so I tabled it. Working with other anchoring for now.
