### ISSUE TITLE
update unity example to ARFoundations 

### ISSUE THREAD

**Issue by yosun** [Azure/azure-spatial-anchors-samples#42]
//TODO

**Comment by shawmakesmusic** [comment]
If you're trying to do cloud anchors today, word is that Google Cloud Anchors are working with ARFoundation already with minimal modifications, avail on the Unity forum. Hopefully it's some pressure for Microsoft to get it together ASAP, since ARFoundation is the only non-deprecated way to access modern AR now.

**Comment by yosun** [comment]
> If you're trying to do cloud anchors today, word is that Google Cloud Anchors are working with ARFoundation already with minimal modifications, avail on the Unity forum. Hopefully it's some pressure for Microsoft to get it together ASAP, since ARFoundation is the only non-deprecated way to access modern AR now.

Don't Google Cloud Anchors still have the 24 hour resolve time limitation? Azure Spatial Anchors is a fundamentally different solution due to real long term persistency and the ability to work with cross-platform pointcloud sets.

**Comment by shawmakesmusic** [comment]
Yeah, there's a reason I'm tracking this git, and also I'm literally the person who told you to use AR Foundation three weeks ago and you called me an idiot and said Vuforia was the only choice for production sooooooo

**Comment by shawmakesmusic** [comment]
All fun aside, Spatial Anchors are basically cripple until the underlying ARKit and Core versions are on parity with the ones in ARFoundation. I've got all the right pointers in place but the buck stops at the DLL.

**Comment by shawmakesmusic** [comment]
Oh yeah, I was actually trying to be helpful-- ASA and GCA are virtually identical under the hood, in terms of the application of ORB SLAM2 in the cloud and capturing an interval of frames with the relative transformation matrix from ARKit/Core to resolve to. Switching one for another is about 6 hours of work if you have a decent abstraction layer. Other than the weird restrictions around use and persistence, they are similar enough algorithmically and workflow that it's a hack. 

Also, if you start using things that work, it encourages the companies things that don't work to get up to parity, which is why we pretend like GCA is the holy grail of persistent solutions :)

**Comment by vriveras** [comment]
We are currently working on ARFoundation It will be part of the SDK supported platforms.

**Comment by yosun** [comment]
Hi Vicente - thanks for the update, what’s your timeline or ETA for when
this will be avail?
-- 
Yosun Chang, Founder and CTO

I'm apparently the only solo woman AR creator interviewed on the SIGGRAPH
blog:
https://blog.siggraph
.org/2019/01/with-mobile-ar-you-can-graffiti-on-the-mona-lisa.html/

Phone: (415) 779 6786
WWW: AReality3D.com
Twitter: @yosun

**Comment by craigktreasure** [comment]
Azure Spatial Anchors 1.3.0 now supports ARFoundation.
