### ISSUE TITLE
 Azure Cosmos DB -- Requests Count too high

### ISSUE THREAD

**Issue by TiNovTec** [Azure/azure-spatial-anchors-samples#54]
( I refer to this page: Tutorial: **Share Azure Spatial Anchors across sessions and devices with an Azure Cosmos DB back end** ( https://docs.microsoft.com/en-us/azure/spatial-anchors/tutorials/tutorial-use-cosmos-db-to-store-anchors ))

I use the demo version from **August 6th**.

I installed the app on Android, launched it the very first time and placed three anchors successfully and also found these anchors in other sessions.. but my Cosmos DB now shows "Total Requests: 993"..... ( before it was zero ) -Isn't this a little bit too much for playing around for 5 minutes, three anchors and only one user ?
_Can I set the update cycle in Unity to reduce the costs ?_

Edit:
I just asked the app ( only ) for an anchor number that does not exist and it added 300+ requests ( currently 1,32K ) only to tell me that this anchor doesn't exist. oO
Really.. something must be wrong. I would rather expect around a 100th part of the requests shown.

**Comment by TiNovTec** [comment]
And after a long weekend ( Thursday - Monday ) I have 3k requests and an invoice of nearly $10 !
Wooow.. what's going on there [?] 
[Image with details](https://imgur.com/a/rp88ujY)

**Comment by vriveras** [comment]
@TiNovTec , Hi can you share if you change some of the sample code? We are not able to repro this. From the images you shared it looks like someone or something is hitting your service and causing the traffic. The code in the samples only do this at the time or storing or recalling an id while the app is running.

**Comment by TiNovTec** [comment]
@vriveras I didn't change any code. I simply followed the tutorial and tested the app on Android.

**Comment by RamonArguelles** [comment]
Hi @TiNovTec,

Check the account Name that you used to deploy your CosmosDB instance? Do not post it here, though, just check it. Perhaps you used one of the sample names mentioned in the Tutorial (ccdbtable, or newtable)? The thing is, once you create a CosmosDB instance, it is public, and if anyone else in the world uses a connection string that matches your Account Name, it will hit your deployed instance. As we mention in the tutorial, we recommend to enter a unique name to identify your Azure CosmosDB account, so that only your own app hits it using your connection string.

**Comment by craigktreasure** [comment]
Closing this issue. Feel free to re-open for further discussion.
